### ISSUE TITLE
/modules/iyzicocheckoutform/controllers/front/result.php

### ISSUE THREAD

**Issue by metineren** [kahvedigital/iyzico-prestashop#7]
/modules/iyzicocheckoutform/controllers/front/result.php
192. satır
if(!empty($error_msg)){

Bu satırdaki ünlemi kaldırın.

**Comment by metineren** [comment]
@kahvedigital @heheok sonuç gösterimiyle ilgili bir hata buldum. Hata mesajı boşsa native gösterilecek hatanın tanımlandığı yerdeki if' te fazladan ünlem var.
Bu ünlem sebebiyle boş dönüş sayfası gösteriliyor.
İlgilenirseniz sevinirim :)

**Comment by kahvedigital** [comment]
Merhabalar,
Gerekli incelemeler sağlanıp düzeltme sağlanacaktır.

**Comment by kahvedigital** [comment]
İlginiz için teşşekür ederiz gerekli düzenlemeler sağlanmıştır.
